# AgroFresh Info Chat - Agricultural Products Information Assistant
# Demo agent for AgroFresh Solutions website
# Focus: Product information, crop management, agricultural solutions

agent_type: "simple_chat"
account: "agrofresh"
instance_name: "agro_info_chat1"
name: "AgroFresh Assistant"
description: "Agricultural products and solutions information assistant for AgroFresh Solutions"

# System prompt configuration
prompts:
  system_prompt_file: "./system_prompt.md"

model_settings:
  model: "moonshotai/kimi-k2-0905"  # Reliable model with great Pydantic AI support
  temperature: 0.3
  max_tokens: 2000

tools:
  vector_search:
    enabled: false  # Disabled - no vector data loaded for AgroFresh yet
    max_results: 5
    similarity_threshold: 0.7
    namespace_isolation: true
    pinecone:
      index_name: "salient-dev-01"
      index_host: "https://salient-dev-01-e1nildl.svc.aped-4627-b74a.pinecone.io"
      namespace: "agrofresh_products"  # Reserved for future use
      embedding_model: "text-embedding-3-small"
      dimensions: 1536
      metric: "cosine"
  
  web_search:
    enabled: false  # Disabled - use direct LLM knowledge only
    provider: "exa"
    engines:
      exa:
        api_key_env: "EXA_API_KEY"
        max_results: 10
      tavily:
        api_key_env: "TAVILY_API_KEY"
        max_results: 10
  
  conversation_management:
    enabled: true
    auto_summarize_threshold: 10
    summary_model: "moonshotai/kimi-k2-0905"

context_management:
  history_limit: 50
  context_window_tokens: 8000
  summarization:
    enabled: true
    trigger_threshold: 10
    summary_length: 200

dependencies:
  vector_db_required: false  # No vector data yet
  session_required: true
  account_context: true  # Multi-tenant architecture enabled

